language: Java
jdk:
- openjdk11
before_install:
- chmod +x mvnw
script: mvn clean package -DskipTests
after_success:
- echo "${DOCKER_USER} / ${REPO} / ${VERSION_MAJOR}.${TRAVIS_BUILD_NUMBER}"
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker build -t ${DOCKER_USER}/${REPO}:${VERSION_MAJOR}.${TRAVIS_BUILD_NUMBER} .
- docker push ${DOCKER_USER}/${REPO}:${VERSION_MAJOR}.${TRAVIS_BUILD_NUMBER}
- docker tag ${DOCKER_USER}/${REPO}:${VERSION_MAJOR}.${TRAVIS_BUILD_NUMBER} ${DOCKER_USER}/${REPO}:latest
- docker push ${DOCKER_USER}/${REPO}:latest
env:
  global:
  - DOCKER_USER=maxeasy2
  - VERSION_MAJOR=1.0
  - REPO=simple-file
  - secure: bmwOOJDzV75YAM1TaYBWSgnDf+LdKRV8JzQjYpo5oM+ABOV+2PujJ9heGMxanwazSYfZp3GY9x+7C/tluMfgdqoRn8XSEh9q/+DWK+DdJrceALM/sikXmDNWN2ReBb3CXYaLjCyA7Tdy53Jwo3WWJBLktdz98n2UU9EdMUZnS5KOId1YBZE2aMnkHUbFiRTB2SQNJBHIazfbRC0RUj68gCVemMZsyn1AwP5UVgja0iQM73xuebiG4JRNqIzsb6k3G472nOUT7HvTpSyM98QLod8l3n8vjmq+kLdBnqcBdXr4XfDKm+zACRJsmJuq7DkD80w0L3qCBy7Z4D3IPim7ZtKhCLdmeFA/BxUcxBvlW1iNvWCbfoyEbEOXRgZHRsd7UVGR+ELaq8OgcFJN5QeN7EF8TX3dYN/vtU5b23SzK+Lft9xCTiPZhZQWjNvwRp1J58UYsYOyav54ydSfgrYReGER9owJICgM1Lq3kqRW6tBAb70ppORPcdRmEYYd4zkft8+4+qaS19tShjrcqBEmVg4Tzxy5uQV5W2TXa8+2qccW/Hn1me4lkI76ltsiSQJhjQFgy9hqJ2/B6xxLlVxT/qTFvzoj7u/I5QMvENoWDPY+0WG/ysgWAOA5QvOjzumrP2VtwsjMaUxjnYoOkC0GjiBid4z8Zs0qRaWF65XziME=
